start migration more web endpoints to sqlx
rust-lang/docs.rs pull request #2311
Opened 2023-11-09 16:27 UTC by syphar

refs #874 

This migrates more web endpoints to sqlx. 

Notable omissions around `Limits` and `CrateDetails`, which should be async too, but I wanted to leave them for another PR. 

Also I want to find a better way to use async in tests, bestrefs #874 

This migrates more web endpoints to sqlx. 

Notable omissions around `Limits` and `CrateDetails`, which should be async too, but I wanted to leave them for another PR. 

Also I want to find a better way to use async in tests, best case even using `tokio::test` or even `sqlx::test`, at the least some `async_wrapper` that enables you to write `.await` in tests. Also for a separate PR.  case even using `tokio::test` or even `sqlx::test`, at the least some `async_wrapper` that enables you to write `.await` in tests. Also for a separate PR. 

Last think I also didn't do is parallelization of independent queries in a single handler, which could be investigated separately.

2023-11-09 17:23 UTC, syphar commented
interesting test failure, I remember running the tests locally and it worked, will try again

2023-11-09 21:20 UTC, Nemo157 requested changes

2023-11-09 21:20 UTC, Nemo157 commented on src/web/sitemap.rs
> +                MAX(releases.release_time) as release_time
```suggestion
                MAX(releases.release_time) as "release_time!"
```

This is non-null, sqlx's inference just can't see through the `MAX` call. (Which will remove the `.map().unwrap_or_default()` below too).

2023-11-09 21:37 UTC, Nemo157 commented
> at the least some `async_wrapper` that enables you to write `.await` in tests.

I had a quick look at this. The biggest blocker is that all the database calls in the test fakes need to be moved over too, otherwise they error like

```
thread 'web::releases::tests::get_releases_by_stars' panicked at postgres-0.19.7/src/config.rs:449:44:
Cannot start a runtime from within a runtime. This happens because a function (like `block_on`) attempted to block the current thread while the thread is being used to drive asynchronous tasks.
```

It's also non-trivial because of the higher-ranked lifetimes meaning that closures don't work, I think the best approach might be to use a macro to wrap the tests giving an API like

```rust
async_tests! {
    async fn foo(env: &TestEnvironment) -> Result<()> {
        ...
    }
}
```

You can see my experiment in the wrapper here, with the inner `async fn` used instead of a closure to have the lifetimes work: <https://github.com/rust-lang/docs.rs/compare/master...Nemo157:docs.rs:test-async-wrapper>.

2023-11-10 05:17 UTC, syphar commented
> It's also non-trivial because of the higher-ranked lifetimes meaning that closures don't work, I think the best approach might be to use a macro to wrap the tests giving an API like

I remember I made it work by using an async closure + `Rc` for the `TestEnvironment`, but in general I'll look into this separately. 

> I had a quick look at this. The biggest blocker is that all the database calls in the test fakes need to be moved over too, otherwise they error like

yep, the sync/async mix makes some things a little ugly until more is migrated.

2023-11-15 10:43 UTC, syphar commented
I accidentally amended other changes from #2312 to the release-time-nullable commit, so now I just squashed them all to avoid more confusion.

2023-11-15 10:56 UTC, Nemo157 approved these changes

2023-11-15 11:42 UTC, merged