Remove more template filters
rust-lang/docs.rs pull request #2608
Opened 2024-09-18 15:39 UTC by GuillaumeGomez

2024-09-18 15:39 UTC, GuillaumeGomez commented
Some more are coming. I found a bug in `rinja` so we will make a new bugfix release soon hopefully.

2024-09-19 05:25 UTC, syphar requested changes
awesome improvements! 

nit: rustfmt :)

2024-09-19 10:30 UTC, GuillaumeGomez commented
Merged then. :)

2024-09-19 10:50 UTC, syphar approved these changes

2024-09-19 10:50 UTC, merged